"""insert_default_employee_types

Revision ID: 3bf4ec2474c3
Revises: f12565b39847
Create Date: 2025-12-17 12:31:13.102590

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3bf4ec2474c3"
down_revision = "f12565b39847"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    conn.execute(
        sa.text("""
            INSERT INTO employee_types (name, code, description, is_active) VALUES 
            ('Сотрудник', 'employee', 'Обычный сотрудник организации', true),
            ('Руководитель', 'manager', 'Руководитель подразделения или отдела', true),
            ('Администратор', 'administrator', 'Администратор системы', true)
            ON CONFLICT (code) DO NOTHING
        """)
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    conn.execute(
        sa.text("""
            DELETE FROM employee_types 
            WHERE code IN ('employee', 'manager', 'administrator')
        """)
    )
    # ### end Alembic commands ###
