"""drop_unique_for_employee

Revision ID: e0977be82069
Revises: 3bf4ec2474c3
Create Date: 2025-12-17 15:27:31.095485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0977be82069'
down_revision = '3bf4ec2474c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employees_telegram_id_key'), 'employees', type_='unique')
    op.create_unique_constraint('uq_employee_telegram_organization', 'employees', ['telegram_id', 'organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_telegram_organization', 'employees', type_='unique')
    op.create_unique_constraint(op.f('employees_telegram_id_key'), 'employees', ['telegram_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
