"""add_version

Revision ID: f12565b39847
Revises: f09e7daacbbe
Create Date: 2025-12-16 17:37:37.443390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12565b39847'
down_revision = 'f09e7daacbbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'version')
    # ### end Alembic commands ###
