"""add_organization_id_for_criteria

Revision ID: f5447bfcdd5f
Revises: e0977be82069
Create Date: 2025-12-18 18:49:13.210274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5447bfcdd5f'
down_revision = 'e0977be82069'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criteria', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'criteria', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'criteria', type_='foreignkey')
    op.drop_column('criteria', 'organization_id')
    # ### end Alembic commands ###
